-- זריעת המלאי המדויק מהמערכת הקיימת (upsert — לא מוחק, מחליף לפי id)
insert into inventory (id, category, name, qty, min_qty, unit) values
  ('inv-1','oneTime','נייר קטן ללחם',150,20,'יח'),
  ('inv-2','oneTime','כוסות שייק',400,20,'יח'),
  ('inv-3','oneTime','בקבוקים',150,10,'יח'),
  ('inv-4','oneTime','קשים',200,20,'יח'),
  ('inv-5','oneTime','קערת סלט קטנה',100,10,'יח'),
  ('inv-6','oneTime','קערת סלט גדולה',70,10,'יח'),
  ('inv-7','oneTime','שקית לאריזה',250,20,'יח'),
  ('inv-8','oneTime','רוטב קטן',0,20,'יח'),
  ('inv-9','oneTime','רוטב גדול',1000,10,'יח'),
  ('inv-10','oneTime','תבנית קטנה לאפייה (שחור-זהב)',450,10,'יח'),
  ('inv-11','afterBirth','ערכה של שפרה ופועה מל״ש',20,3,'יח'),
  ('inv-12','afterBirth','הסבר שמן אתרי',0,5,'יח'),
  ('inv-13','afterBirth','הדפסות צבעוניות',0,5,'יח'),
  ('inv-14','afterBirth','שוקלד',0,5,'יח'),
  ('inv-15','afterBirth','שוברים',0,5,'יח'),
  ('inv-16','afterBirth','פתק הסבר שפרה ופועה',0,5,'יח'),
  ('inv-17','afterBirth','שמן אתרי לתינוק',0,5,'יח'),
  ('inv-18','pregnancy','סוכריות מציצה',0,5,'שקיות'),
  ('inv-19','pregnancy','דוגמיות סימני מתיחה',0,5,'יח'),
  ('inv-20','pregnancy','בקבוק מים',0,5,'יח'),
  ('inv-21','pregnancy','שמן לידה של יהודית',0,3,'יח'),
  ('inv-22','pregnancy','שובר השאלת TENS',0,3,'יח'),
  ('inv-23','pregnancy','שובר הפרשת חלה',0,5,'יח'),
  ('inv-24','pregnancy','תהילים + שיר המעלות',0,5,'יח'),
  ('inv-25','yearGift','משחק לילד',0,5,'יח'),
  ('inv-26','yearGift','מגנט',0,5,'יח'),
  ('inv-27','yearGift','גרבר ללא סוכר',0,5,'יח'),
  ('inv-28','yearGift','תהילים אישי',0,5,'יח'),
  ('inv-29','yearGift','ספרון מתנת גיל שנה',25,3,'יח')
on conflict (id) do update set
  category = excluded.category,
  name = excluded.name,
  qty = excluded.qty,
  min_qty = excluded.min_qty,
  unit = excluded.unit;
